### ISSUE TITLE
Magnetorquer

### ISSUE THREAD

**Issue by niki100jad** [kongr45gpen/POQUITO-panels#6]
I moved everything around to avoid interference with the magnetorquer. Also, the coil size has been changed compared to the previous version to fit better. We need a connector (input 1, input 2) on the upper part of the board to send pulses to magnetorquers. But I am not sure about cabling in the PocketQube. Feel free to add the connector the way you think is better, and also please let me know if I should change anything.

**Comment by kongr45gpen** [comment]
Connections added in https://github.com/kongr45gpen/POQUITO-panels/commit/1c432ae6b6167d89f3beedf9c007300833087981.

![image](https://github.com/kongr45gpen/POQUITO-panels/assets/720678/6c0be6c3-5d30-4e1a-8a15-5865bb825772)

I also moved some vias closer to the center because KiCad was complaining that they were too close to the MTQ traces.
